spring:
    jmx: 
        enabled: false
javafx:
    stage:
        resizable: true
    title: 12306抢票


schedule :
  jobs :
    -
      cronExpression : '0/15 * * * * ? '
      dataToWrite : job 1
#    -
#      cronExpression : '* 0/6 * * * ? '
#      dataToWrite : job 2
#    -
#      cronExpression : '* 0/3 * * * ? '
#      dataToWrite : job 3
#    -
#      cronExpression : '* 0/3 * * * ? '
#      dataToWrite : job 4
#    -
#      cronExpression : '* 0/6 * * * ? '
#      dataToWrite : job 5
#    -
#      cronExpression : '* 0/3 * * * ? '
#      dataToWrite : job 6
#    -
#      cronExpression : '* 0/3 * * * ? '
#      dataToWrite : job 7
#    -
#      cronExpression : '* 0/6 * * * ? '
#      dataToWrite : job 8
#    -
#      cronExpression : '* 0/3 * * * ? '
#      dataToWrite : job 9